#!/usr/bin/env python

import rospy
from mir_joint_space_controller_ros.joint_space_controller import JointSpaceController

if __name__ == "__main__":
    rospy.init_node('joint_space_controller')
    JSC = JointSpaceController()
    CONTROL_RATE = rospy.get_param('~control_rate', 5.0)
    RATE = rospy.Rate(CONTROL_RATE)
    rospy.on_shutdown(JSC.publish_zero_vel)
    try:
        while not rospy.is_shutdown():
            JSC.run_once()
            RATE.sleep()
    except Exception as e:
        if type(e) != rospy.ROSInterruptException:
            rospy.logerr(str(e))
    rospy.loginfo('Exiting.')
